### ISSUE TITLE
Issues in setting up this project in eclipse.

### ISSUE THREAD

**Issue by harika-mamidi** [OhadR/Authentication-Flows-client#15]
Hi OhadR, 

I was not able to make this project working in eclipse. It will be of great help if you can guide me with the same. 

Thanks,
Harika

**Comment by OhadR** [comment]
Could you please post this question in stackoverflow.com and i will answer there? This way it might help others in the future.
There is a tag in stackoverflow for "authentication flows"; please tag your question and I will try to help there.
Please add your error in the question.

Thanks!
Ohad

**Comment by harika-mamidi** [comment]
sure :) thanks a lot for immediate reply.
