### ISSUE TITLE
How to build on linux.

### ISSUE THREAD

**Issue by ggmartins** [OhadR/Authentication-Flows-client#16]
Hey there,
first of all. Congratulations for this great initiative! I was trying to build/run without success. I've posted at  http://stackoverflow.com/questions/31036369/how-to-solve-could-not-find-artifact-com-ohadrauthentication-flows
Thanks,

GM

**Comment by OhadR** [comment]
solved?

**Comment by ggmartins** [comment]
yes, thanks
