### ISSUE TITLE
crypto.BadPaddingException: Given final block not properly padded

### ISSUE THREAD

**Issue by tmpg** [OhadR/Authentication-Flows-client#19]
Every so often I get a:
Decryption error and I traced it back to:
java aes javax.crypto.BadPaddingException: Given final block not properly padded

Have any of you ran into this before? I can not figure out what is going wrong...

**Comment by tmpg** [comment]
I found the issue...

It appears that if I reset the webapp, it fails to decrypt it. Is it adding a server specific value to the hash? If so, could you point it out to me? This will eventually be an issue but I will put it on the back burner till then.

Any help will be greatly appreciated.

Since I haven't said so already. I would like to say thank you to everyone on this project, it taught me a lot.

Best Regards,
tmpg

**Comment by OhadR** [comment]
Thanks for the warm words!

can you please open a case inhttp://www.StackOverflow.com
http://www.stackoverflow.com/ on this, and tag "authentication-flows"?
Other people in the community can help you out, especially as this is not
seem to be specific issue of this module...

http://stackoverflow.com/questions/tagged/authentication-flows

**Comment by tmpg** [comment]
opened on stackoverflow

**Comment by tmpg** [comment]
http://stackoverflow.com/questions/34690255/authentication-flows-email-urls-do-not-work-after-web-server-reset

**Comment by OhadR** [comment]
thanks for opening the issue in SO. 
As I've answered there, every time your web-app loads, Spring loads all the beans. Among them are Crypto's library beans, such as CryptoUtil and CryptoProvider, and if you look carefully you will notice on DefaultCryptoProvider.loadMasterKeys() that a new key is generated.

I believe that explains the behavior you see.
