### ISSUE TITLE
Password change link is still active after password is changed

### ISSUE THREAD

**Issue by paweljarosz83** [OhadR/Authentication-Flows-client#21]
As the title says, if you intercept an URL from the email, you can change user's password skipping all
security mechanisms. Easy to test: just copy an URL, change the password, paste the URL and change the password again and again. Shouldn't be hard to fix:) Other than that - great project.

**Comment by OhadR** [comment]
it seems to be the server's side issue, so kindly open this issue in https://github.com/OhadR/oAuth2-sample/issues. This repository is a client-sample for the authentication flows, which is in the link i've pasted.

**Comment by OhadR** [comment]
issue is relevant to the back-end (this is "only" sample client-app). so issue was opened there (see above) and this one is to be closed.

**Comment by OhadR** [comment]
@paweljarosz83 , thanks for opening this issue. I've opened a related issue in the server's project, and committed code that solves this enhancement.

regards,
